version: '3.8'

services:
  db:
    image: postgres
    container_name: tcit-postgresql
    environment:
      POSTGRES_DB: tcit
      POSTGRES_USER: tcit
      POSTGRES_PASSWORD: tcit
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: